src/main/java/com/example/demo/DemoApplication.java
src/main/java/com/example/demo/domain/auth/api/AuthController.java
src/main/java/com/example/demo/domain/auth/application/AuthService.java
src/main/java/com/example/demo/domain/auth/dto/request/JoinRequest.java
src/main/java/com/example/demo/domain/user/domain/User.java
src/main/java/com/example/demo/domain/user/repository/UserRepository.java
src/main/java/com/example/demo/global/base/dto/ErrorResponse.java
src/main/java/com/example/demo/global/base/exception/ErrorCode.java
src/main/java/com/example/demo/global/base/exception/GlobalExceptionHandler.java
src/main/java/com/example/demo/global/base/exception/ServiceException.java
src/main/java/com/example/demo/global/config/auth/SecurityConfig.java

- 회원가입 기능 구현
- ErrorResponse 직렬화 문제 해결
- ServiceException 인자 간소화
- 회원가입 기능 구현
- `HttpMediaTypeNotAcceptableException` 발생
- ErrorResponse에 `@Getter` 넣어줘서 해결
- ServiceException 인자 간소화
- 기존 code, message, params을 받던 부분을, ErrorCode만 받아서 상위 `RuntimeException`으로 메시지만 던져주는 형식으로 변경
- 추후 테스트 코드 + 로그인 기능 구현 후 관련 이슈 닫을 예정

[#10] 회원가입 기능 구현 & ErrorResponse 직렬화 문제 해결

---

src/docs/asciidoc/auth.adoc
src/main/java/com/example/demo/domain/auth/api/AuthController.java
src/main/java/com/example/demo/domain/auth/application/AuthService.java
src/main/java/com/example/demo/domain/auth/dto/response/LoginResponse.java
src/main/java/com/example/demo/global/auth/token/application/TokenProvider.java
src/main/java/com/example/demo/global/auth/token/domain/RefreshToken.java
src/main/java/com/example/demo/global/auth/token/filter/JwtFilter.java
src/main/java/com/example/demo/global/auth/token/repository/RefreshTokenRepository.java
src/main/java/com/example/demo/global/base/exception/ErrorCode.java
src/main/java/com/example/demo/global/config/auth/SecurityConfig.java
src/main/java/com/example/demo/global/config/web/WebConfig.java
src/main/java/com/example/demo/global/utils/CookieUtil.java
src/main/java/com/example/demo/global/utils/HttpServletUtil.java
src/test/java/com/example/demo/domain/auth/api/AuthControllerTest.java

- Refresh Token 구현
- 구현전에 고민한 내용을 벨로그를 통해 정리해봤습니다. 동작방식만 참고하시면 될 것 같고, 코드에 대한 피드백 주시면 감사하겠습니당
- https://velog.io/@kimgunwooo/Refresh-%ED%86%A0%ED%81%B0-%EB%B6%80%EC%88%98%EA%B8%B0
- 재발급 API를 구현한 것이 아닌, filter에 로직을 추가해서 구현했기에 RestDocs 파일은 존재하지 않습니다.
resolves #18

[#18] Refresh Token 구현

---

build.gradle
src/docs/asciidoc/index.adoc
src/docs/asciidoc/post.adoc
src/main/java/com/example/demo/domain/file/FileController.java
src/main/java/com/example/demo/domain/file/FileUploader.java
src/main/java/com/example/demo/domain/file/domain/FileNameInfo.java
src/main/java/com/example/demo/domain/file/domain/entity/UploadFile.java
src/main/java/com/example/demo/domain/file/uploader/FileS3Uploader.java
src/main/java/com/example/demo/domain/file/uploader/FileSysStore.java
src/main/java/com/example/demo/domain/file/uploader/FileUploader.java
src/main/java/com/example/demo/domain/post/controller/PostController.java
src/main/java/com/example/demo/domain/post/domain/request/PostRequest.java
src/main/java/com/example/demo/domain/post/domain/response/PostInfoResponse.java
src/main/java/com/example/demo/domain/post/service/PostService.java
src/main/java/com/example/demo/global/base/exception/ErrorCode.java
src/main/java/com/example/demo/global/config/s3/AmazonS3Config.java
src/main/resources/application-file.yml
src/main/resources/application-s3.yml
src/main/resources/application.yml
src/test/java/com/example/demo/domain/file/controller/FileControllerTest.java
src/test/java/com/example/demo/domain/post/Repository/PostRepositoryTest.java
src/test/java/com/example/demo/domain/post/controller/PostControllerTest.java

- 빌드 오류 해결
- s3 파일 업로드 기능 추가
- post 관련 test 코드 추가 및 restdocs 추가
- FileS3Uploader 클래스
- 테스트 코드
- 명세서
resolves #28

[#28] S3 파일 업로드 기능 추가

---

src/docs/asciidoc/post.adoc
src/main/java/com/example/demo/domain/post/Repository/PostRepository.java
src/main/java/com/example/demo/domain/post/controller/PostController.java
src/main/java/com/example/demo/domain/post/domain/page/PageInfo.java
src/main/java/com/example/demo/domain/post/domain/page/PageSort.java
src/main/java/com/example/demo/domain/post/domain/page/PageTitleInfo.java
src/main/java/com/example/demo/domain/post/domain/response/PostPageResponse.java
src/main/java/com/example/demo/domain/post/service/PostService.java
src/main/java/com/example/demo/domain/user/domain/vo/Track.java
src/main/java/com/example/demo/global/base/exception/GlobalExceptionHandler.java
src/test/java/com/example/demo/DemoApplicationTests.java
src/test/java/com/example/demo/domain/post/controller/PostControllerTest.java
src/test/resources/org/springframework/restdocs/templates/query-parameters.snippet

- 게시판 페이징 기능 추가
- 게시판 페이징 테스트 코드 추가
- restdocs 명세서 작성
- restdocs 명세서 쿼리 파라미터 필드 커스텀
- 페이징 관련 controller - service - repository 
- test 코드
- restdocs 필드 커스텀
resolves #30

게시판 페이징 처리

---

src/main/java/com/example/demo/global/config/s3/AmazonS3Config.java
src/main/resources/application-s3.yml

s3 이름 변경 및 깃허브 key에 설정
s3 이름 변경 및 깃허브 key에 설정

[refactor] s3 관련 key 리팩터링

---

src/main/java/com/example/demo/domain/board/controller/BoardController.java
src/main/java/com/example/demo/domain/board/domain/entity/Board.java
src/main/java/com/example/demo/domain/board/domain/request/BoardRequest.java
src/main/java/com/example/demo/domain/board/domain/response/BoardInfoResponse.java
src/main/java/com/example/demo/domain/board/service/BoardService.java
src/main/java/com/example/demo/domain/category/domain/entity/BoardCategory.java
src/main/java/com/example/demo/domain/category/repository/BoardCategoryRepository.java
src/main/java/com/example/demo/domain/user/domain/User.java
src/test/java/com/example/demo/domain/board/Repository/BoardRepositoryTest.java
src/test/java/com/example/demo/domain/board/service/BoardServiceTest.java

- 게시물 조회 test 코드 작성
- 게시물 수정 로직 구현
- 게시물 수정 test 코드 작성
- BoardService update 로직 의존성이 너무 많이 생기는데 불필요한 코드나 개선사항 위주로 봐주세요
- repository test 빌드 오류 해결 못함 -> 주석처리
#37

[#37] board update 로직 구현 및 Service Test 코드 작성

---

build.gradle
src/main/java/com/example/demo/domain/auth/api/AuthController.java
src/main/java/com/example/demo/domain/auth/application/AuthService.java
src/main/java/com/example/demo/domain/auth/application/CustomUserDetailsService.java
src/main/java/com/example/demo/domain/auth/domain/UserContext.java
src/main/java/com/example/demo/domain/auth/dto/request/JoinRequest.java
src/main/java/com/example/demo/domain/auth/dto/request/LoginRequest.java
src/main/java/com/example/demo/domain/auth/security/CustomAccessDeniedHandler.java
src/main/java/com/example/demo/domain/auth/security/CustomAuthenticationEntryPoint.java
src/main/java/com/example/demo/domain/auth/security/LoginAuthenticationFailureHandler.java
src/main/java/com/example/demo/domain/auth/security/LoginAuthenticationFilter.java
src/main/java/com/example/demo/domain/auth/security/LoginAuthenticationProvider.java
src/main/java/com/example/demo/domain/auth/security/LoginAuthenticationSuccessHandler.java
src/main/java/com/example/demo/domain/board/controller/BoardController.java
src/main/java/com/example/demo/domain/comment/controller/CommentController.java
src/main/java/com/example/demo/domain/comment/domain/response/CommentInfoResponse.java
src/main/java/com/example/demo/domain/file/controller/FileController.java
src/main/java/com/example/demo/domain/user/api/UserController.java
src/main/java/com/example/demo/domain/user/application/UserService.java
src/main/java/com/example/demo/domain/user/domain/User.java
src/main/java/com/example/demo/domain/user/domain/vo/Role.java
src/main/java/com/example/demo/global/base/exception/ErrorCode.java
src/main/java/com/example/demo/global/base/exception/GlobalExceptionHandler.java
src/main/java/com/example/demo/global/config/auth/SecurityConfig.java
src/main/resources/application-security.yml

- User 세팅 변경
- 로그인 기능 구현
- 로컬 세션으로 구현
- 서버 오토스케일링을 고려해서 redis로 구현해야할지 고민.
- redis 라는 비싼 db를 사용하면서까지 우리 서버가 커질까..?
- SecurityContextHolder에 저장되는 인증 객체 이름 변경
- UserPrincipal -> UserContext
resolves #40

[#40] 로그인 기능 구현

---

src/test/java/com/example/demo/domain/category/repository/CategoryRepositoryTest.java

[#37] repository test 주석처리

---

src/main/java/com/example/demo/domain/newsletter/domain/Newsletter.java
src/main/java/com/example/demo/domain/report/api/ReportController.java
src/main/java/com/example/demo/domain/report/application/ReportService.java
src/main/java/com/example/demo/domain/report/domain/Report.java
src/main/java/com/example/demo/domain/report/dto/ReportResponse.java
src/main/java/com/example/demo/domain/report/repository/ReportRepository.java
src/main/java/com/example/demo/domain/seminar_application/domain/SeminarApplication.java
src/main/java/com/example/demo/domain/user/api/UserController.java
src/main/java/com/example/demo/domain/user/application/UserService.java
src/main/java/com/example/demo/domain/user/domain/User.java
src/main/java/com/example/demo/domain/user/dto/request/CompleteRegistrationRequest.java
src/main/java/com/example/demo/domain/user/dto/request/UserUpdateRequest.java
src/main/java/com/example/demo/global/aop/UserIdInjectionAspect.java
src/main/java/com/example/demo/global/base/exception/ErrorCode.java
src/main/java/com/example/demo/global/config/auth/JwtConfig.java
src/main/java/com/example/demo/global/config/auth/SecurityConfig.java
src/main/java/com/example/demo/global/jwt/JwtHandler.java
src/main/java/com/example/demo/global/jwt/controller/TokenController.java
src/main/java/com/example/demo/global/jwt/domain/RefreshToken.java
src/main/java/com/example/demo/global/jwt/dto/TokenRequest.java
src/main/java/com/example/demo/global/jwt/dto/TokenResponse.java
src/main/java/com/example/demo/global/jwt/repository/RefreshTokenRepository.java
src/main/java/com/example/demo/global/jwt/service/TokenService.java
src/test/java/com/example/demo/base/ControllerTest.java

- 토큰 재발급 api
- 추가정보 입력 api
- 신고 기능 api
- aop : userId 위치에 따른 오류 수정
- 간단한 api 구현 및 여러 자잘한 오류를 수정했습니다.
- 추가로 기획 변경에 따른 domain 관계를 수정했습니다.
resolves #이슈번호

enh : 자잘한 기능 구현 및 오류 수정

---

.github/workflows/ci-gradle-build.yml

- 기존 workflows 파일을 CI만 동작하도록 수정
- 추가로 PR이 올라갔을 때에도 동작하도록 설정
resolves #이슈번호

fix : ci workflows

---

.github/workflows/cicd-gradle-build.yml

enh : CI/CD 구현 (ecs 이미지 교체까지)

---

src/test/java/com/example/demo/global/oauth/service/CustomOAuth2UserServiceTest.java

- OAuth Provider가 제공하는 데이터가 OAuth2User에 주입되는지 확인하는 테스트 코드 작성
- OAuth 서버에서 응답한 데이터가 잘 주입되는지 확인하기 위해 `CustomOAuth2UserService`를 테스트하는 게 필요하다고 생각했는데 정말 필요한지 궁금합니다.
- OAuth 모의 서버를 만들 때 [블로그 게시글](https://velog.io/@tjddus0302/%EC%99%B8%EB%B6%80-API-%EB%A5%BC-%EC%9D%98%EC%A1%B4%ED%95%98%EB%8A%94-OAuth-%ED%85%8C%EC%8A%A4%ED%8A%B8%ED%95%98%EA%B8%B0)을 참고하여 따로 컨트롤러를 만들기보다 `MockRestServiceServer`을 사용하는게 나아보였는데 어떤지 궁금합니다.
- 중복된 부분이 많은데 수정 방향이 있을까요?
- 현재 테스트 클래스의 패키지가 올바른지 확인 부탁드립니다.
- API 문서를 참고하면서 작성했는데 모의 서버가 실제와 다른 부분이 있는지 확인 부탁드립니다.
resolves #이슈번호

CustomOAuth2UserService 테스트 코드 작성

---

build.gradle
docker-compose-dev.yml
src/main/java/com/example/demo/domain/board/service/repository/BoardRepository.java
src/main/java/com/example/demo/domain/board/service/view/implement/ViewBulkUpdater.java
src/main/java/com/example/demo/domain/board/service/view/implement/ViewEagerIncreaseUpdater.java
src/main/java/com/example/demo/global/aop/log/ExceptionLogExplanation.java
src/main/java/com/example/demo/global/aop/log/GeneralLogExplanation.java
src/main/java/com/example/demo/global/aop/log/LogExplanations.java
src/main/java/com/example/demo/global/aop/log/aspect/ApiMonitorAspect.java
src/main/java/com/example/demo/global/aop/log/aspect/ExceptionAspect.java
src/main/java/com/example/demo/global/aop/log/aspect/ProdLogAspect.java
src/main/java/com/example/demo/global/aop/log/implement/ApiTimer.java
src/main/java/com/example/demo/global/aop/log/pointcut/LogPointCut.java
src/main/java/com/example/demo/global/log/properties/ExceptionLogProperty.java
src/main/java/com/example/demo/global/log/properties/InfoLogProperty.java
src/main/java/com/example/demo/global/log/properties/LogLevel.java
src/main/java/com/example/demo/global/log/properties/LogProperty.java
src/main/java/com/example/demo/infra/board/repository/BoardRepositoryImpl.java
src/main/resources/application-dev.yml
src/main/resources/application-local.yml
src/main/resources/application-prod.yml
src/main/resources/log/log-local.xml
src/main/resources/log/log-prod.xml
src/main/resources/logback.xml
src/test/java/com/example/demo/application/board/integration/BoardServiceIntegrationTest.java

- Actuator 엔드포인트 설정과 프로덕션 환경에서 엑추에이터 설정 구성
- 로깅 설정 구성 ( 로키를 위한 로그 파일로 출력)
- api latency 측정을 위한 micrometer 로직 구현 ApiMonitorAspect.class
- 에러 발생시 로그 출력 AOP 구현 ExceptionAspect.class
- 조회수 증가 로직 개선 전으로 롤백
-  사유: 초기엔 지연된 증가보단 즉시 증가를 위해서
- 기존에 사용하던 로그 AOP local 디버깅 용 제외 전부 Deprecated 시킴
resolves #90

모니터링 환경 및 로깅 세팅

---

.github/workflows/prod-cicd.yml
src/main/java/com/example/demo/global/config/db/RedisConfig.java
src/main/java/com/example/demo/global/config/db/properties/RedisProperties.java
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml

- production 환경 DB (mysql , redis ) 설정 구성했습니다.
- redis는 비밀번호 추가했습니다
- cicd 구성했습니다
이상한 점 말씀해주세요!
resolves #이슈번호

production 환경 cicd 및 설정 파일 변경

---

src/main/java/com/example/demo/application/board/dto/request/BoardUpdateRequest.java

- [qa 시에 발견된 validation 에러 수정] 게시글 헤드 이미지 -> 필수 아닌걸로 수정

fix: qa 시에 발견된 validation 에러 수정

---

src/main/java/com/example/demo/infra/user_additional_info/entity/UserAdditionalInfo.java

- enum필드인 StudentStatus에  @Enumerated(EnumType.STRING)를 추가했습니다.
resolves #이슈번호

UserAdditionalIfo 필드 수정

---

src/main/java/com/example/demo/global/regex/S3UrlRegex.java
src/main/java/com/example/demo/global/utils/S3UrlUtil.java

- 이미지 url validation 한글이랑 특수문자 가능하게 변경

이미지 url validation 한글이랑 특수문자 가능하게 변경

---

src/main/java/com/example/demo/domain/newsletter/strategy/BaseEmailDeliveryStrategy.java
src/main/java/com/example/demo/domain/newsletter/strategy/MentoringNoticeEmailDeliveryStrategy.java
src/main/java/com/example/demo/domain/newsletter/strategy/ProjectNoticeEmailDeliveryStrategy.java
src/main/java/com/example/demo/domain/newsletter/strategy/SeminarSummaryEmailDeliveryStrategy.java
src/main/java/com/example/demo/domain/newsletter/strategy/StudyNoticeEmailDeliveryStrategy.java

- 스터디, 멘토링, 프로젝트 모집 및 세미나 정리 글 등록 시 발송되는 이메일 내의 링크를 수정합니다.
resolves #이슈번호

발송되는 뉴스레터 이메일 내 링크 수정

---

src/main/java/com/example/demo/application/board/controller/BoardController.java

- /api/v1/boards/{} -> 권한 문제 해결

prod 환경 hotfix 반영

---

src/main/java/com/example/demo/infra/board/querydsl/BoardDslRepositoryImpl.java

 페이징 오류 해결

---

src/main/java/com/example/demo/application/user/dto/request/CompleteRegistrationRequest.java

hotfix: 프로필 이미지 변경 오류 급한 수정

---

src/main/java/com/example/demo/application/user/dto/request/ChangeProfileUrlRequest.java
src/main/java/com/example/demo/application/user/dto/request/CompleteRegistrationRequest.java

hotfix: 프로필 url 주석처리
